### ISSUE TITLE
How to remove catalog source

### ISSUE THREAD

**Issue by adhikarexuss** [oracle/oci-service-operator#5]
I was following the installation guide for OCI Service Operator for Kubernetes (OSOK) from the following this link:
https://github.com/oracle/oci-service-operator/blob/main/docs/installation.md

I have successfully installed the operator-sdk and OLM.
However, when I wanted to deploy OSOK, I missed the step of pulling the docker image.
So, I straight away ran this command:
`operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0`

according to the installation guide, I should've pull the docker image first
`$ docker pull iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0`

so, it gave me an error like this:

```
INFO[0028] Successfully created registry pod: iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0 
INFO[0028] Created CatalogSource: oci-service-operator-catalog 
INFO[0029] OperatorGroup "operator-sdk-og" created    
INFO[0029] Created Subscription: oci-service-operator-v1-0-0-sub 
FATA[0124] Failed to run bundle: install plan is not available for the subscription oci-service-operator-v1-0-0-sub: timed out waiting for the condition
```

I noticed that it created a pod called "iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0" so I deleted the pod
```kubectl delete pod iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0```

And it gave me this message
```pod "iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0" deleted```

Then when I ran the command
```operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0```

It returned with the following error message
```
FATA[0004] Failed to run bundle: create catalog: error creating catalog source: catalogsources.operators.coreos.com "oci-service-operator-catalog" already exists
```

How can I remove that catalog completely so I can execute the operator-sdk run bundle command again?
Environment

**Kubernetes cluster type:**

Kubernetes on Oracle Cloud Infrastructure

```$ operator-sdk version```

```
operator-sdk version: "v1.13.0", commit: "6e84414b468029c5c3e07352cabe64cf3a682111", kubernetes version: "1.21", go version: "go1.16.8", GOOS: "linux", GOARCH: "amd64"
```

```$ kubectl version```

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"50317190d44dbdb51ae7ff430917b32ba96188b5", GitTreeState:"clean", BuildDate:"2021-06-30T14:20:31Z", GoVersion:"go1.15.13 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Comment by adhikarexuss** [comment]
Hi @jayasheelankumar thank you so much for the reply.
I was able to execute the command successfully.
```
$ operator-sdk cleanup oci-service-operator
INFO[0002] subscription "oci-service-operator-v1-0-0-sub" deleted 
INFO[0002] catalogsource "oci-service-operator-catalog" deleted 
INFO[0002] operatorgroup "operator-sdk-og" deleted      
INFO[0002] Operator "oci-service-operator" uninstalled  
```
So now, I'm going to repeat the steps of installing the oci-service-operator again.
I'm checking the docker image as shown below.

`$ docker image ls`

```
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
iad.ocir.io/oracle/oci-service-operator-bundle   1.0.0               4037f7ec880d        2 months ago        31.7kB
```

Then I executed the following command
`$ operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.0.0`
This is the result
```
INFO[0022] Successfully created registry pod: iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0 
INFO[0022] Created CatalogSource: oci-service-operator-catalog 
INFO[0023] OperatorGroup "operator-sdk-og" created      
INFO[0023] Created Subscription: oci-service-operator-v1-0-0-sub 
FATA[0121] Failed to run bundle: install plan is not available for the subscription oci-service-operator-v1-0-0-sub: timed out waiting for the condition
```

How do I resolve that error?

When I ran the `kubectl` command to check on the pods created, this is what I'm getting.

```
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                   READY   STATUS    RESTARTS   AGE
default       iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0   0/1     Error     4          4m40s
kube-system   coredns-5ccc698744-d88r4                               1/1     Running   0          37d
kube-system   coredns-5ccc698744-hmqbg                               1/1     Running   0          19d
.
.
.
olm           catalog-operator-765c45774c-lfwg5                      1/1     Running   0          24d
olm           olm-operator-9bb87877b-7fcvg                           1/1     Running   0          24d
olm           operatorhubio-catalog-h4km2                            1/1     Running   0          37h
olm           packageserver-6984ff9888-l9khg                         1/1     Running   0          24d
olm           packageserver-6984ff9888-v5plw                         1/1     Running   0          24d
```
I truncated the result

This is the result after the second time I'm running the `kubectl get pods`
```
$ kubectl get pods
NAME                                                   READY   STATUS             RESTARTS   AGE
iad-ocir-io-oracle-oci-service-operator-bundle-1-0-0   0/1     CrashLoopBackOff   5          7m13s
```

Do you know what I'm doing wrong here?

**Comment by jayasheelankumar** [comment]
I guess the previous clean-up might not be done appropriately. I guess that could leave the bundle subscription to timeout. Can you try to clean up using the above command and try again? If it is failing even after that. Can you try to restart the OLM operator pods and try again?

**Comment by mnemonic01** [comment]
Install the bundle ends up in a failure
 operator-sdk run bundle iad.ocir.io/oracle/oci-service-operator-bundle:1.1.1 -n oci-service-operator-system

The pod ends in CrashLoopBackOff
Look into the pod there's a permission problem:
2022-07-10T19:37:05.808Z | mkdir: can't create directory '/database': Permission denied

Do you know what might causes this?
